### ISSUE TITLE
1.1 update - I would love to help out :)

### ISSUE THREAD

**Issue by ruyanve** [NanoCE/Glass_N_Lights#10]
Hey man, thanks for the comment on my clutter door mod on steam, I am using your mod since it first came out!

I forked this and made the 1.1 xml and folder changes needed, you only need to recompile with the new harmony. https://github.com/ruyanve/Glass_N_Lights/tree/1.1
Pardeike wrote really good instructions for it here: https://gist.github.com/pardeike/08ff826bf40ee60452f02d85e59f32ff

Hope you find some time, I know the drill... I am renovating a medium sized house between working a 9-5. Time is hard to come by, take care and keep it up!

**Comment by NanoCE** [comment]
Im not sure if anything came of this but Im sorry I didn't respond. I never noticed a notification for this and just stumbled upon this post now. My memory is a bit hazy and while I do recall commenting on your workshop page, I don't recall what I said and it looks like the comment was deleted. 

I would imagine this was your help in regards to my update for the new 1.1 Rimworld patch which is probably why you closed this comment a day later. I feel bad for not noticing this sooner, feel free to send me a pm on steam in the future, I normally accept most friend requests that have at least a few hours on Rimworld.
