### ISSUE TITLE
Trader bug

### ISSUE THREAD

**Issue by mjdcurtis** [NanoCE/Glass_N_Lights#17]
**Describe the bug**
Getting a weird bug, presumably from an interaction with another mod. It messes up caravans and trade with industrial factions to the point where I cannot trade

**To Reproduce**
Trade with an industrial faction. Inspect inventory of industrial faction.

**Expected behavior**
Regular trading

System.InvalidOperationException: Sequence contains no elements
at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00010] in <351e49e2a5bf4fd6beabb458ce2255f3>:0
at RimWorld.GenStuff.DefaultStuffFor (Verse.BuildableDef bd) [0x00145] in <f51597c720ac4bec9b4bfc9070cc723e>:0
at RimWorld.StockGenerator_Armor.HandlesThingDef (Verse.ThingDef td) [0x00014] in <f51597c720ac4bec9b4bfc9070cc723e>:0
at RimWorld.TraderKindDef.WillTrade (Verse.ThingDef td) [0x00010] in <f51597c720ac4bec9b4bfc9070cc723e>:0
at RimWorld.Dialog_SellableItems.CalculateSellableItems (RimWorld.TraderKindDef trader) [0x00068] in <f51597c720ac4bec9b4bfc9070cc723e>:0
at RimWorld.Dialog_SellableItems..ctor (RimWorld.ITrader trader) [0x00058] in <f51597c720ac4bec9b4bfc9070cc723e>:0
at RimWorld.Planet.Settlement.<GetGizmos>b__61_0 () [0x00005] in <f51597c720ac4bec9b4bfc9070cc723e>:0
at Verse.Command_Action.ProcessInput (UnityEngine.Event ev) [0x00007] in <f51597c720ac4bec9b4bfc9070cc723e>:0
at Verse.GizmoGridDrawer.DrawGizmoGrid (System.Collections.Generic.IEnumerable`1[T] gizmos, System.Single startX, Verse.Gizmo& mouseoverGizmo, System.Func`2[T,TResult] customActivatorFunc, System.Func`2[T,TResult] highlightFunc, System.Func`2[T,TResult] lowlightFunc) [0x006a6] in <f51597c720ac4bec9b4bfc9070cc723e>:0
at (wrapper dynamic-method) RimWorld.InspectGizmoGrid.RimWorld.InspectGizmoGrid.DrawInspectGizmoGridFor_Patch0(System.Collections.Generic.IEnumerable`1<object>,Verse.Gizmo&)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch3 (string)
Verse.Log:ErrorOnce (string,int)
(wrapper dynamic-method) RimWorld.InspectGizmoGrid:RimWorld.InspectGizmoGrid.DrawInspectGizmoGridFor_Patch0 (System.Collections.Generic.IEnumerable`1<object>,Verse.Gizmo&)
RimWorld.Planet.WorldInspectPane:DrawInspectGizmos ()
RimWorld.InspectPaneUtility:ExtraOnGUI (RimWorld.IInspectPane)
RimWorld.Planet.WorldInspectPane:ExtraOnGUI ()
Verse.WindowStack:WindowStackOnGUI ()
(wrapper dynamic-method) RimWorld.UIRoot_Play:RimWorld.UIRoot_Play.UIRootOnGUI_Patch2 (RimWorld.UIRoot_Play)
(wrapper dynamic-method) Verse.Root:Verse.Root.OnGUI_Patch1 (Verse.Root)

**Comment by NanoCE** [comment]
Please also upload your modlist. 

How are you confirming that it's my mod? I'm not saying it's not but I don't see any relation. Please give more info, thank you.

**Comment by mjdcurtis** [comment]
I'm sure it's some other moders fault. I have installed a stupid number of them. Happy to close the issue, just thought you might be interested.

I confirmed it by removing the mod and then trading works normally.

It has something to do with the settlements generating the list of tradable items.

Here is what I was running for the latest test minus glass + lights.

[Mod list length: 253]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
BetterLoading [https://steamcommunity.com/sharedfiles/filedetails/?id=1999454301]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Ideology [Official DLC] [https:// no link (local mod)]
PatchOperationHighlander [https://steamcommunity.com/sharedfiles/filedetails/?id=2552002158]
Startup impact [https://steamcommunity.com/sharedfiles/filedetails/?id=1684944322]
SRTS Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1845423808]
[ELIF] SRTS - Helicopters [https://steamcommunity.com/sharedfiles/filedetails/?id=2575097304]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
Achtung! [https://steamcommunity.com/sharedfiles/filedetails/?id=730936602]
Age Matters 2.0 [1.2+] [https://steamcommunity.com/sharedfiles/filedetails/?id=2264291966]
A Dog Said... Animal Prosthetics [https://steamcommunity.com/sharedfiles/filedetails/?id=746425621]
Cherry Picker (dev) [https://steamcommunity.com/sharedfiles/filedetails/?id=2633276599]
Vanilla Expanded Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2023507013]
Alpha Animals [https://steamcommunity.com/sharedfiles/filedetails/?id=1541721856]
Dubs Bad Hygiene [https://steamcommunity.com/sharedfiles/filedetails/?id=836308268]
Toggleable Overlays [https://steamcommunity.com/sharedfiles/filedetails/?id=2608654598]
[KV] RimFridge [https://steamcommunity.com/sharedfiles/filedetails/?id=1180721235]
LWM's Deep Storage [https://steamcommunity.com/sharedfiles/filedetails/?id=1617282896]
Vanilla Factions Expanded - Ancients [https://steamcommunity.com/sharedfiles/filedetails/?id=2654846754]
Bill Doors' Useful Junks [https:// no link (local mod)]
Vanilla Books Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2193152410]
Vanilla Factions Expanded - Mechanoids [https://steamcommunity.com/sharedfiles/filedetails/?id=2329011599]
[SYR] Universal Fermenter [https://steamcommunity.com/sharedfiles/filedetails/?id=2558008936]
Vanilla Factions Expanded - Settlers [https://steamcommunity.com/sharedfiles/filedetails/?id=2052918119]
Vanilla Weapons Expanded - Coilguns [https://steamcommunity.com/sharedfiles/filedetails/?id=2375692535]
Vanilla Weapons Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814383360]
Vanilla Weapons Expanded - Heavy Weapons [https://steamcommunity.com/sharedfiles/filedetails/?id=2329126791]
Vanilla Weapons Expanded - Laser [https://steamcommunity.com/sharedfiles/filedetails/?id=1989352844]
Vanilla Weapons Expanded - Frontier [https://steamcommunity.com/sharedfiles/filedetails/?id=2454918139]
[LITE]Expanded Materials - Metals [https://steamcommunity.com/sharedfiles/filedetails/?id=2434786884]
Vanilla Cooking Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2134308519]
Vanilla Fishing Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1914064942]
Vanilla Ideology Expanded - Memes and Structures [https://steamcommunity.com/sharedfiles/filedetails/?id=2636329500]
Alpha Memes [https:// no link (local mod)]
Animal Gear [https://steamcommunity.com/sharedfiles/filedetails/?id=1541438907]
Animal Equipment [https://steamcommunity.com/sharedfiles/filedetails/?id=2568865984]
Animal Medical Bed [https://steamcommunity.com/sharedfiles/filedetails/?id=2016958187]
Animal Namer [https://steamcommunity.com/sharedfiles/filedetails/?id=2229408147]
AnimalHarvestingSpot (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=1542765654]
AnimalHarvestingSpot ReTexture [https://steamcommunity.com/sharedfiles/filedetails/?id=2437966351]
Animals Logic [https://steamcommunity.com/sharedfiles/filedetails/?id=1098354593]
Animals are fun [https://steamcommunity.com/sharedfiles/filedetails/?id=2108362126]
Area Inclusion & Exclusion [https://steamcommunity.com/sharedfiles/filedetails/?id=2033828736]
Area Unlocker [https://steamcommunity.com/sharedfiles/filedetails/?id=725153576]
Argon's Basic Components [https://steamcommunity.com/sharedfiles/filedetails/?id=2525478396]
Armor Racks [https://steamcommunity.com/sharedfiles/filedetails/?id=1875828205]
Pharmacist [https://steamcommunity.com/sharedfiles/filedetails/?id=1365242717]
ReGrowth: Core and Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2260097569]
Argón's Tribal Medicine [https://steamcommunity.com/sharedfiles/filedetails/?id=2310530147]
Auto tool switcher [https://steamcommunity.com/sharedfiles/filedetails/?id=2588418157]
Automatic Night Owl [https://steamcommunity.com/sharedfiles/filedetails/?id=2056012179]
Children, school and learning [https://steamcommunity.com/sharedfiles/filedetails/?id=1541438230]
Babies and Children [1.3] [https://steamcommunity.com/sharedfiles/filedetails/?id=2559574784]
Backup Power [https://steamcommunity.com/sharedfiles/filedetails/?id=2084493662]
Barely Restricted Spots [https://steamcommunity.com/sharedfiles/filedetails/?id=2492243369]
Beautiful Bodies [https://steamcommunity.com/sharedfiles/filedetails/?id=2068281501]
Ben Lubar presents: Vanilla Books Expanded Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2650429441]
Bionic icons [https://steamcommunity.com/sharedfiles/filedetails/?id=1677616980]
Vanilla Brewing Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2186560858]
Vanilla Factions Expanded - Insectoids [https://steamcommunity.com/sharedfiles/filedetails/?id=2149755445]
Vanilla Factions Expanded - Medieval [https://steamcommunity.com/sharedfiles/filedetails/?id=2023513450]
Vanilla Furniture Expanded - Production [https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632]
Vanilla Furniture Expanded - Security [https://steamcommunity.com/sharedfiles/filedetails/?id=1845154007]
Ben Lubar's Vanilla Expanded Patches [https://steamcommunity.com/sharedfiles/filedetails/?id=2655869813]
Best Mix (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2195986094]
Better Pawn Control [https://steamcommunity.com/sharedfiles/filedetails/?id=1541460369]
Better Workbench Management [https://steamcommunity.com/sharedfiles/filedetails/?id=935982361]
Blueprints [https://steamcommunity.com/sharedfiles/filedetails/?id=708455313]
Desks are better than blackboards - CSL Retexture [https://steamcommunity.com/sharedfiles/filedetails/?id=2557348220]
CSL Blackboard Retexture [https://steamcommunity.com/sharedfiles/filedetails/?id=2559456394]
Allow Tool [https://steamcommunity.com/sharedfiles/filedetails/?id=761421485]
Dubs Mint Menus [https://steamcommunity.com/sharedfiles/filedetails/?id=1446523594]
Categorized Bill Dropdown [https://steamcommunity.com/sharedfiles/filedetails/?id=2625720098]
Choice Of Psycasts [https://steamcommunity.com/sharedfiles/filedetails/?id=2293460251]
Clean Pathfinding [https://steamcommunity.com/sharedfiles/filedetails/?id=2603765747]
Cleaning Priority (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2018316486]
Colony Manager [https://steamcommunity.com/sharedfiles/filedetails/?id=715565262]
Common Sense [https://steamcommunity.com/sharedfiles/filedetails/?id=1561769193]
Compact Hediffs [https://steamcommunity.com/sharedfiles/filedetails/?id=2031734067]
Convert Then Enslave [https:// no link (local mod)]
Convert Then Recruit [https:// no link (local mod)]
Dismiss Trader (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2078518511]
Dubs Apparel Tweaks [https://steamcommunity.com/sharedfiles/filedetails/?id=2296697286]
Dubs Skylights [https://steamcommunity.com/sharedfiles/filedetails/?id=833899765]
Salted Meat 2.0 [https://steamcommunity.com/sharedfiles/filedetails/?id=2606419180]
[SYR] Processor Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2633514537]
Rimefeller [https://steamcommunity.com/sharedfiles/filedetails/?id=1321849735]
Vanilla Factions Expanded - Vikings [https://steamcommunity.com/sharedfiles/filedetails/?id=2231295285]
Vanilla Plants Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2134308522]
Dogs mate (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2441132298]
DontBlockDoor [https://steamcommunity.com/sharedfiles/filedetails/?id=1691076769]
Drug Policy Fix (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2195390245]
Dubs Central Heating [https://steamcommunity.com/sharedfiles/filedetails/?id=2619214952]
Dubs Mint Minimap [https://steamcommunity.com/sharedfiles/filedetails/?id=1662119905]
Dubs Performance Analyzer [https://steamcommunity.com/sharedfiles/filedetails/?id=2038874626]
Dubs Rimatomics [https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465]
Earlier Trenches (VFE - Security Patch) [https://steamcommunity.com/sharedfiles/filedetails/?id=2605662978]
Vanilla Expanded - Royalty Patches [https://steamcommunity.com/sharedfiles/filedetails/?id=2260012940]
Electric Braziers [https://steamcommunity.com/sharedfiles/filedetails/?id=2555623506]
Elmo's More Dryads Adopted [https:// no link (local mod)]
[NL] Facial Animation - WIP [https://steamcommunity.com/sharedfiles/filedetails/?id=1635901197]
Faces of the Rim - Facial Animation [https://steamcommunity.com/sharedfiles/filedetails/?id=2555107849]
Faces of the Rim - Dizzy Colors [https://steamcommunity.com/sharedfiles/filedetails/?id=2565622912]
Faster Aging (unofficial 1.3 Update) [https://steamcommunity.com/sharedfiles/filedetails/?id=2559815752]
Fixable Mood Debuffs Alert [https://steamcommunity.com/sharedfiles/filedetails/?id=1307316672]
Flickable Storage [https://steamcommunity.com/sharedfiles/filedetails/?id=2497907804]
Food Alert (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2017538067]
Cash Register [https://steamcommunity.com/sharedfiles/filedetails/?id=2506046833]
Gastronomy [https://steamcommunity.com/sharedfiles/filedetails/?id=2279786905]
Grains and Brewing [https://steamcommunity.com/sharedfiles/filedetails/?id=2453613013]
Graphics Settings+ [https://steamcommunity.com/sharedfiles/filedetails/?id=1678847247]
RWLayout [https://steamcommunity.com/sharedfiles/filedetails/?id=2209393954]
Work Tab [https://steamcommunity.com/sharedfiles/filedetails/?id=725219116]
Grouped Pawns Lists [https://steamcommunity.com/sharedfiles/filedetails/?id=2340773428]
HD Pawn Rendering [https://steamcommunity.com/sharedfiles/filedetails/?id=2538746878]
Holsters [https:// no link (local mod)]
Hospitality [https://steamcommunity.com/sharedfiles/filedetails/?id=753498552]
Ignore Idle Guests [https://steamcommunity.com/sharedfiles/filedetails/?id=2515048728]
Job In Bar [https://steamcommunity.com/sharedfiles/filedetails/?id=2086300611]
LBE's A Dog Said Easy Patcher [https://steamcommunity.com/sharedfiles/filedetails/?id=944381237]
LWM's Fuel Filter [https://steamcommunity.com/sharedfiles/filedetails/?id=2461634904]
Labels on Floor [https://steamcommunity.com/sharedfiles/filedetails/?id=1408863965]
Little Storage 2 [https://steamcommunity.com/sharedfiles/filedetails/?id=2166580060]
Loading In Progress [https://steamcommunity.com/sharedfiles/filedetails/?id=1975622772]
Map Reroll [https://steamcommunity.com/sharedfiles/filedetails/?id=761315214]
Meals On Wheels [https://steamcommunity.com/sharedfiles/filedetails/?id=1323773476]
Anima Animals [https://steamcommunity.com/sharedfiles/filedetails/?id=2339084391]
Vanilla Animals Expanded — Caves [https://steamcommunity.com/sharedfiles/filedetails/?id=2576512001]
Vanilla Animals Expanded — Desert [https://steamcommunity.com/sharedfiles/filedetails/?id=1849183875]
Vanilla Animals Expanded — Tropical Swamp [https://steamcommunity.com/sharedfiles/filedetails/?id=1907283935]
Vanilla Animals Expanded — Tundra [https://steamcommunity.com/sharedfiles/filedetails/?id=1895364585]
Medical Tab [https://steamcommunity.com/sharedfiles/filedetails/?id=715565817]
Mod Medicine Patch [https://steamcommunity.com/sharedfiles/filedetails/?id=1430084631]
Moonlight [https://steamcommunity.com/sharedfiles/filedetails/?id=2589384830]
More Ideological Words [https://steamcommunity.com/sharedfiles/filedetails/?id=2643795171]
More Psycasts [https://steamcommunity.com/sharedfiles/filedetails/?id=2460833332]
More Than Capable [https://steamcommunity.com/sharedfiles/filedetails/?id=1803932954]
Mortar Accuracy [https://steamcommunity.com/sharedfiles/filedetails/?id=1729446857]
No Version Warning [https://steamcommunity.com/sharedfiles/filedetails/?id=2599504692]
Owl's Colonist Bar (dev) [https:// no link (local mod)]
Packed Sand and Dirt [https://steamcommunity.com/sharedfiles/filedetails/?id=2493275334]
Performance Optimizer [https:// no link (local mod)]
Permeable Terrain [https://steamcommunity.com/sharedfiles/filedetails/?id=2629981384]
Perspective: Trees [https://steamcommunity.com/sharedfiles/filedetails/?id=2572022990]
Pocket Sand [https://steamcommunity.com/sharedfiles/filedetails/?id=2226330302]
Power Alerts [https://steamcommunity.com/sharedfiles/filedetails/?id=1664714758]
Powerful Psycast AI [https://steamcommunity.com/sharedfiles/filedetails/?id=2026063610]
Prepare Moderately [https://steamcommunity.com/sharedfiles/filedetails/?id=2057362949]
Prison Commons [https://steamcommunity.com/sharedfiles/filedetails/?id=2630896782]
Prisoners Are Not Swines [https://steamcommunity.com/sharedfiles/filedetails/?id=2613966365]
Prune Job [https://steamcommunity.com/sharedfiles/filedetails/?id=2621614316]
QualityBuilder [https://steamcommunity.com/sharedfiles/filedetails/?id=754637870]
QualitySurgeon [https://steamcommunity.com/sharedfiles/filedetails/?id=857350593]
Quarry [https://steamcommunity.com/sharedfiles/filedetails/?id=2007576583]
RIMMSqol [https://steamcommunity.com/sharedfiles/filedetails/?id=1084452457]
RT Fuse [https://steamcommunity.com/sharedfiles/filedetails/?id=728314182]
RT Power Switch [https://steamcommunity.com/sharedfiles/filedetails/?id=728314859]
Relevant Stats In Description [https:// no link (local mod)]
RenameColony [https://steamcommunity.com/sharedfiles/filedetails/?id=1359645236]
Repairable Gear [https://steamcommunity.com/sharedfiles/filedetails/?id=2482478785]
Replace Stuff [https://steamcommunity.com/sharedfiles/filedetails/?id=1372003680]
Simple Utilities: Wall [https://steamcommunity.com/sharedfiles/filedetails/?id=2565545335]
Replace Stuff Mod Compatibility [https://steamcommunity.com/sharedfiles/filedetails/?id=2642161586]
Replantable Anima Trees [https://steamcommunity.com/sharedfiles/filedetails/?id=2586765823]
Replantable Gauranlen Trees [https://steamcommunity.com/sharedfiles/filedetails/?id=2586767283]
ResearchPal - Forked [https://steamcommunity.com/sharedfiles/filedetails/?id=2351393394]
Rimedieval - Ice add-on [https://steamcommunity.com/sharedfiles/filedetails/?id=2596933598]
Rimsential - Spaceports [https:// no link (local mod)]
Safe Drug Policy Generator [https://steamcommunity.com/sharedfiles/filedetails/?id=2582640021]
Simple FX: Smoke [https://steamcommunity.com/sharedfiles/filedetails/?id=2574489704]
Scattered Flames [https://steamcommunity.com/sharedfiles/filedetails/?id=2652749788]
Scattered Stones [https://steamcommunity.com/sharedfiles/filedetails/?id=2598436855]
Search and Destroy [https://steamcommunity.com/sharedfiles/filedetails/?id=1467764609]
ReGrowth: Boreal Forest Expansion [https://steamcommunity.com/sharedfiles/filedetails/?id=2106597000]
ReGrowth: Cold Bog Expansion [https://steamcommunity.com/sharedfiles/filedetails/?id=2182111148]
ReGrowth: Desert Expansion [https://steamcommunity.com/sharedfiles/filedetails/?id=2466442910]
ReGrowth: Temperate Forest Expansion [https://steamcommunity.com/sharedfiles/filedetails/?id=2261114471]
ReGrowth: Tundra Expansion [https://steamcommunity.com/sharedfiles/filedetails/?id=2107412614]
SeedsPlease: Lite [https://steamcommunity.com/sharedfiles/filedetails/?id=2586052937]
Self Dyeing [https://steamcommunity.com/sharedfiles/filedetails/?id=2562859859]
Share The Load [https://steamcommunity.com/sharedfiles/filedetails/?id=2576277142]
Shit Rimworld Says [https://steamcommunity.com/sharedfiles/filedetails/?id=2069706266]
Simple Utilities: Ceiling [https://steamcommunity.com/sharedfiles/filedetails/?id=2571003732]
Smart Farming [https://steamcommunity.com/sharedfiles/filedetails/?id=2619652663]
Smart Medicine [https://steamcommunity.com/sharedfiles/filedetails/?id=1309994319]
Smart Speed [https://steamcommunity.com/sharedfiles/filedetails/?id=1504723424]
Smart Turret Covering [https://steamcommunity.com/sharedfiles/filedetails/?id=2636621800]
Turn It On and Off - RePowered [https://steamcommunity.com/sharedfiles/filedetails/?id=2228219259]
Therapy [https://steamcommunity.com/sharedfiles/filedetails/?id=1076950211]
Snap Out! [https://steamcommunity.com/sharedfiles/filedetails/?id=1319782555]
Stockpile Ranking [https://steamcommunity.com/sharedfiles/filedetails/?id=1558464886]
Stonecutting Extended [https://steamcommunity.com/sharedfiles/filedetails/?id=2571676542]
Tainted Renaming [https://steamcommunity.com/sharedfiles/filedetails/?id=2021251001]
Toggleable Readouts [https:// no link (local mod)]
Toggleable Shields [https:// no link (local mod)]
Trade Ships Drop Spot [https://steamcommunity.com/sharedfiles/filedetails/?id=1969732297]
Underground Power Conduits [https://steamcommunity.com/sharedfiles/filedetails/?id=1735421319]
Use Bedrolls [https://steamcommunity.com/sharedfiles/filedetails/?id=1353625821]
Vanilla Animals Expanded — Arid Shrubland [https://steamcommunity.com/sharedfiles/filedetails/?id=1836900626]
Vanilla Animals Expanded — Australia [https://steamcommunity.com/sharedfiles/filedetails/?id=1963681588]
Vanilla Animals Expanded — Boreal Forest [https://steamcommunity.com/sharedfiles/filedetails/?id=1895364938]
Vanilla Animals Expanded — Cats and Dogs [https://steamcommunity.com/sharedfiles/filedetails/?id=1823540489]
Vanilla Animals Expanded — Endangered [https://steamcommunity.com/sharedfiles/filedetails/?id=2366589898]
Vanilla Animals Expanded — Extreme Desert [https://steamcommunity.com/sharedfiles/filedetails/?id=1849184079]
Vanilla Animals Expanded — Ice Sheet [https://steamcommunity.com/sharedfiles/filedetails/?id=1895364782]
Vanilla Animals Expanded — Tropical Rainforest [https://steamcommunity.com/sharedfiles/filedetails/?id=1907283872]
VFME - Caravan Packs! [https://steamcommunity.com/sharedfiles/filedetails/?id=2255432128]
Vanilla Animals Expanded — Temperate Forest [https://steamcommunity.com/sharedfiles/filedetails/?id=2260502331]
Vanilla Cooking Expanded - Stews [https://steamcommunity.com/sharedfiles/filedetails/?id=2134312965]
Vanilla Events Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1938420742]
Vanilla Expanded - Ideology Patches [https://steamcommunity.com/sharedfiles/filedetails/?id=2566669771]
Vanilla Factions Expanded - Pirates [https:// no link (local mod)]
Vanilla Fishing Expanded - Fishing Treasures AddOn [https://steamcommunity.com/sharedfiles/filedetails/?id=2468543398]
Vanilla Furniture Expanded - Architect [https://steamcommunity.com/sharedfiles/filedetails/?id=2608762624]
Vanilla Furniture Expanded - Medical Module [https://steamcommunity.com/sharedfiles/filedetails/?id=1718191613]
Vanilla Hair Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1888705256]
Vanilla Ideology Expanded - Dryads [https:// no link (local mod)]
Vanilla Ideology Expanded - Icons and Symbols [https://steamcommunity.com/sharedfiles/filedetails/?id=2552609458]
Vanilla Ideology Expanded - Relics and Artifacts [https://steamcommunity.com/sharedfiles/filedetails/?id=2564895018]
Vanilla Ideology Expanded - Splits and Schisms [https://steamcommunity.com/sharedfiles/filedetails/?id=2573138902]
Vanilla Outposts Expanded [https:// no link (local mod)]
Vanilla Weapons Expanded - Makeshift [https://steamcommunity.com/sharedfiles/filedetails/?id=2419690698]
Variety Matters Improved [https://steamcommunity.com/sharedfiles/filedetails/?id=2353847457]
Veinminer R1.1 [https://steamcommunity.com/sharedfiles/filedetails/?id=1541978411]
We Had a Trader? (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=1541408076]
What's That Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=2258431182]
Dress Patients [https://steamcommunity.com/sharedfiles/filedetails/?id=1667901146]
Wheelchairs [https://steamcommunity.com/sharedfiles/filedetails/?id=2599914280]
Where is my weapon? [https://steamcommunity.com/sharedfiles/filedetails/?id=1539028008]
While You're Up / PUAH+ [https://steamcommunity.com/sharedfiles/filedetails/?id=2034960453]
Windows [https://steamcommunity.com/sharedfiles/filedetails/?id=2571189146]
World Map Beautification Project [https://steamcommunity.com/sharedfiles/filedetails/?id=2314407956]
Yayo's Animation [https://steamcommunity.com/sharedfiles/filedetails/?id=2575938407]
Yayo's Caravan [https://steamcommunity.com/sharedfiles/filedetails/?id=2574818016]
[KV] Trading Spot [https://steamcommunity.com/sharedfiles/filedetails/?id=1180719658]
[KYD] ReFreshed ReGrowth [https:// no link (local mod)]
[LTS] Ammunition [https://steamcommunity.com/sharedfiles/filedetails/?id=2436604824]
[SR]Factional War [https://steamcommunity.com/sharedfiles/filedetails/?id=2534328163]
[SR]Raid Extension [https://steamcommunity.com/sharedfiles/filedetails/?id=2554928098]
[SYR] Doormats [https://steamcommunity.com/sharedfiles/filedetails/?id=1508778962]
[SYR] Terrain [https://steamcommunity.com/sharedfiles/filedetails/?id=1544439671]
JGH Retexture Pack [https://steamcommunity.com/sharedfiles/filedetails/?id=2641840426]
[LCK] No MealVariant Graphics [https:// no link (local mod)]
Vanilla Expanded/Medieval Overhaul Retexture [https://steamcommunity.com/sharedfiles/filedetails/?id=2618375677]
Medieval Overhaul [https://steamcommunity.com/sharedfiles/filedetails/?id=2553700067]
Medieval Overhaul: Leather Patches [https://steamcommunity.com/sharedfiles/filedetails/?id=2611116560]
Different Egg Sizes [https://steamcommunity.com/sharedfiles/filedetails/?id=2625721813]
DocWorld Lite [https:// no link (local mod)]
DocUniversalResources [https:// no link (local mod)]
RocketMan - Performance Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=2479389928]

**Comment by NanoCE** [comment]
nah, I would prefer to narrow down the error. I can implement a null/empty collection check on this specific method and we can go from there. I will probably push an update to GitHub (here) sometime this weekend so be on the lookout for the update/ reply to this message. Thank you for your assistance.

**Comment by NanoCE** [comment]
Life got real busy this past year, if this issue still persists, please open a new issue. Sorry for the inconvience.
